# Site settings
title: Sconsify
email: fabiofalci@gmail.com
description: >
  Your awesome Spotify service now in a client text mode
baseurl: ""
url: "http://www.sconsify.org"
github_username: fabiofalci/sconsify

# Build settings
markdown: kramdown
